import type { SocialPlatform } from "@/types";

export const RESERVED_USERNAMES = [
  "admin",
  "api",
  "app",
  "auth",
  "blog",
  "callback",
  "dashboard",
  "docs",
  "help",
  "login",
  "logout",
  "pricing",
  "privacy",
  "register",
  "reset-password",
  "forgot-password",
  "settings",
  "signup",
  "support",
  "terms",
  "about",
  "contact",
  "features",
  "home",
  "profile",
  "search",
  "status",
  "legal",
  "sparkbio",
  "www",
  "mail",
  "ftp",
  "static",
  "assets",
  "cdn",
  "images",
  "public",
  "en",
  "pt-br",
] as const;

export const USERNAME_REGEX = /^[a-z0-9][a-z0-9-]{1,28}[a-z0-9]$/;

export const SOCIAL_PLATFORMS: {
  platform: SocialPlatform;
  label: string;
  urlPrefix: string;
  icon: string;
}[] = [
  { platform: "instagram", label: "Instagram", urlPrefix: "https://instagram.com/", icon: "instagram" },
  { platform: "tiktok", label: "TikTok", urlPrefix: "https://tiktok.com/@", icon: "music-2" },
  { platform: "youtube", label: "YouTube", urlPrefix: "https://youtube.com/", icon: "youtube" },
  { platform: "x", label: "X (Twitter)", urlPrefix: "https://x.com/", icon: "twitter" },
  { platform: "facebook", label: "Facebook", urlPrefix: "https://facebook.com/", icon: "facebook" },
  { platform: "linkedin", label: "LinkedIn", urlPrefix: "https://linkedin.com/in/", icon: "linkedin" },
  { platform: "github", label: "GitHub", urlPrefix: "https://github.com/", icon: "github" },
  { platform: "twitch", label: "Twitch", urlPrefix: "https://twitch.tv/", icon: "twitch" },
  { platform: "snapchat", label: "Snapchat", urlPrefix: "https://snapchat.com/add/", icon: "ghost" },
  { platform: "pinterest", label: "Pinterest", urlPrefix: "https://pinterest.com/", icon: "palette" },
  { platform: "spotify", label: "Spotify", urlPrefix: "https://open.spotify.com/", icon: "music" },
  { platform: "soundcloud", label: "SoundCloud", urlPrefix: "https://soundcloud.com/", icon: "cloud" },
  { platform: "discord", label: "Discord", urlPrefix: "https://discord.gg/", icon: "message-circle" },
  { platform: "telegram", label: "Telegram", urlPrefix: "https://t.me/", icon: "send" },
  { platform: "whatsapp", label: "WhatsApp", urlPrefix: "https://wa.me/", icon: "phone" },
  { platform: "email", label: "Email", urlPrefix: "mailto:", icon: "mail" },
  { platform: "website", label: "Website", urlPrefix: "", icon: "globe" },
];

export const PLATFORM_BRAND_COLORS: Record<
  import("@/types").SocialPlatform,
  { bg: string; text: string }
> = {
  whatsapp: { bg: "#25D366", text: "#fff" },
  instagram: { bg: "linear-gradient(45deg, #f09433, #e6683c, #dc2743, #cc2366, #bc1888)", text: "#fff" },
  tiktok: { bg: "#000000", text: "#fff" },
  youtube: { bg: "#FF0000", text: "#fff" },
  x: { bg: "#000000", text: "#fff" },
  facebook: { bg: "#1877F2", text: "#fff" },
  linkedin: { bg: "#0A66C2", text: "#fff" },
  github: { bg: "#333333", text: "#fff" },
  twitch: { bg: "#9146FF", text: "#fff" },
  snapchat: { bg: "#FFFC00", text: "#000" },
  pinterest: { bg: "#E60023", text: "#fff" },
  spotify: { bg: "#1DB954", text: "#fff" },
  soundcloud: { bg: "#FF5500", text: "#fff" },
  discord: { bg: "#5865F2", text: "#fff" },
  telegram: { bg: "#26A5E4", text: "#fff" },
  email: { bg: "#EA4335", text: "#fff" },
  website: { bg: "#333333", text: "#fff" },
};

export const THEME_FONTS = [
  { value: "Inter", label: "Inter" },
  { value: "Poppins", label: "Poppins" },
  { value: "Roboto", label: "Roboto" },
  { value: "Open Sans", label: "Open Sans" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Playfair Display", label: "Playfair Display" },
  { value: "Space Grotesk", label: "Space Grotesk" },
  { value: "DM Sans", label: "DM Sans" },
  { value: "Nunito", label: "Nunito" },
  { value: "Raleway", label: "Raleway" },
] as const;

export const THEME_PRESETS = [
  {
    name: "Sparkbio Default",
    bg_color: "#FAFAFA",
    text_color: "#1E1E2E",
    button_color: "#FF6B35",
    button_text_color: "#FFFFFF",
    button_style: "pill" as const,
    button_style_v2: "solid" as const,
    button_corner: "full" as const,
    button_shadow: "none" as const,
    font_family: "Inter",
  },
  {
    name: "Midnight",
    bg_color: "#0F0F23",
    text_color: "#E8E8E8",
    button_color: "#6366F1",
    button_text_color: "#FFFFFF",
    button_style: "rounded" as const,
    button_style_v2: "solid" as const,
    button_corner: "round" as const,
    button_shadow: "none" as const,
    font_family: "Space Grotesk",
  },
  {
    name: "Ocean Breeze",
    bg_color: "#E0F7FA",
    text_color: "#004D40",
    button_color: "#00897B",
    button_text_color: "#FFFFFF",
    button_style: "pill" as const,
    button_style_v2: "solid" as const,
    button_corner: "full" as const,
    button_shadow: "none" as const,
    font_family: "Poppins",
  },
  {
    name: "Sunset",
    bg_color: "#FFF3E0",
    text_color: "#BF360C",
    button_color: "#FF5722",
    button_text_color: "#FFFFFF",
    button_style: "rounded" as const,
    button_style_v2: "solid" as const,
    button_corner: "round" as const,
    button_shadow: "none" as const,
    font_family: "Montserrat",
  },
  {
    name: "Rose Gold",
    bg_color: "#FDF2F8",
    text_color: "#831843",
    button_color: "#EC4899",
    button_text_color: "#FFFFFF",
    button_style: "pill" as const,
    button_style_v2: "solid" as const,
    button_corner: "full" as const,
    button_shadow: "none" as const,
    font_family: "Playfair Display",
  },
  {
    name: "Forest",
    bg_color: "#F1F8E9",
    text_color: "#1B5E20",
    button_color: "#4CAF50",
    button_text_color: "#FFFFFF",
    button_style: "rounded" as const,
    button_style_v2: "solid" as const,
    button_corner: "round" as const,
    button_shadow: "none" as const,
    font_family: "DM Sans",
  },
  {
    name: "Lavender Dream",
    bg_color: "#F3E5F5",
    text_color: "#4A148C",
    button_color: "#9C27B0",
    button_text_color: "#FFFFFF",
    button_style: "shadow" as const,
    button_style_v2: "solid" as const,
    button_corner: "round" as const,
    button_shadow: "hard" as const,
    font_family: "Nunito",
  },
  {
    name: "Minimal",
    bg_color: "#FFFFFF",
    text_color: "#111111",
    button_color: "#111111",
    button_text_color: "#FFFFFF",
    button_style: "sharp" as const,
    button_style_v2: "solid" as const,
    button_corner: "square" as const,
    button_shadow: "none" as const,
    font_family: "Inter",
  },
  {
    name: "Neon",
    bg_color: "#1A1A2E",
    text_color: "#EAEAEA",
    button_color: "#E94560",
    button_text_color: "#FFFFFF",
    button_style: "pill" as const,
    button_style_v2: "solid" as const,
    button_corner: "full" as const,
    button_shadow: "none" as const,
    font_family: "Space Grotesk",
  },
  {
    name: "Cream",
    bg_color: "#FFFDE7",
    text_color: "#3E2723",
    button_color: "#795548",
    button_text_color: "#FFFFFF",
    button_style: "outline" as const,
    button_style_v2: "outline" as const,
    button_corner: "round" as const,
    button_shadow: "none" as const,
    font_family: "Raleway",
  },
  {
    name: "Electric Blue",
    bg_color: "#E3F2FD",
    text_color: "#0D47A1",
    button_color: "#2196F3",
    button_text_color: "#FFFFFF",
    button_style: "pill" as const,
    button_style_v2: "solid" as const,
    button_corner: "full" as const,
    button_shadow: "none" as const,
    font_family: "Roboto",
  },
  {
    name: "Charcoal",
    bg_color: "#263238",
    text_color: "#CFD8DC",
    button_color: "#FF9800",
    button_text_color: "#263238",
    button_style: "rounded" as const,
    button_style_v2: "solid" as const,
    button_corner: "round" as const,
    button_shadow: "none" as const,
    font_family: "Open Sans",
  },
] as const;

export const PREMADE_GRADIENTS = [
  { name: "Sunset", from: "#FF512F", to: "#DD2476" },
  { name: "Ocean", from: "#2E3192", to: "#1BFFFF" },
  { name: "Peach", from: "#FFDEE9", to: "#B5FFFC" },
  { name: "Lavender", from: "#C471F5", to: "#FA71CD" },
  { name: "Mint", from: "#0BAB64", to: "#3BB78F" },
  { name: "Dusk", from: "#2C3E50", to: "#FD746C" },
  { name: "Cotton Candy", from: "#E8CBC0", to: "#636FA4" },
  { name: "Aurora", from: "#00C9FF", to: "#92FE9D" },
  { name: "Ember", from: "#F7971E", to: "#FFD200" },
] as const;

export const AVATAR_MAX_SIZE = 2 * 1024 * 1024; // 2MB
export const AVATAR_ACCEPTED_TYPES = ["image/jpeg", "image/png", "image/webp", "image/gif"];

export const PLANS = {
  free: {
    name: "Free",
    price: 0,
  },
  pro: {
    name: "Pro",
    monthlyPrice: 9,
    yearlyPrice: 7,
    yearlyTotal: 84,
    trialDays: 7,
  },
} as const;
